apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visitor-counter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/ai-devops-cloud/eks-deploy.git
    targetRevision: main
    path: charts/visitor-counter
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: latest
  
  destination:
    server: https://kubernetes.default.svc
    namespace: visitor-counter
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas